name: Vote - Build Scan Push (ECR)

on:
  push:
    branches: ["main"]
    paths:
      - "vote/**"
      - ".github/workflows/vote-ecr-trivy.yaml"
  pull_request:
    branches: ["main"]
    paths:
      - "vote/**"
      - ".github/workflows/call-docker-build-vote.yaml"

permissions:
  contents: read
  id-token: write
  security-events: write

env:
  AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REPO: ${{ secrets.ECR_REPO}}

jobs:
  vote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: docker build -t vote:latest ./vote

      - name: Trivy scan
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: "vote:latest"
          format: "sarif"
          output: "trivy-vote.sarif"
          severity: "CRITICAL,HIGH"
          exit-code: "0"

      - name: Upload Trivy results
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: "trivy-vote.sarif"

      - name: Push to ECR (main only)
        if: github.event_name == 'push' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        run: |
          IMAGE="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}:latest"
          docker tag vote:latest "$IMAGE"
          docker push "$IMAGE"



