name: Result - Build Scan Push (ECR)

on:
  push:
    branches: ["main"]
    paths:
      - "result/**"
      - ".github/workflows/call-docker-build-result.yaml"
  pull_request:
    branches: ["main"]
    paths:
      - "result/**"
      - ".github/workflows/result-ecr-trivy.yaml"

permissions:
  contents: read
  id-token: write
  security-events: write

env:
  AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REPO: ${{ secrets.ECR_REPO }}
  SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

jobs:
  result:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      
      - name: SonarQube Scan (Result)
        uses: SonarSource/sonarqube-scan-action@v5
        with:
          projectBaseDir: result
          args: >
            -Dsonar.projectKey=result
            -Dsonar.sources=.

      - name: Build Docker image
        run: docker build -t result:v2.1 ./result

      - name: Trivy scan
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: "result:v2.1"
          format: "sarif"
          output: "trivy-result.sarif"
          severity: "CRITICAL,HIGH"
          exit-code: "0"

      - name: Upload Trivy results
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: "trivy-result.sarif"

      - name: Configure AWS (OIDC)
        if: github.event_name == 'push' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        if: github.event_name == 'push' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        uses: aws-actions/amazon-ecr-login@v2

      - name: Push to ECR (main only)
        if: github.event_name == 'push' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        run: |
          IMAGE="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}:v2"
          docker tag result:v2.1 "$IMAGE"
          docker push "$IMAGE"